name: Publish opkg feed

on:
  release:
    types: [published]

jobs:
  publish-opkg:
    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v6

      - name: Download smhub release asset
        uses: robinraju/release-downloader@v1
        with:
          repository: ${{ github.repository }}
          tag: ${{ github.event.release.tag_name }}
          fileName: "go-tydom_Linux_riscv64.tar.gz"
          extract: true
          extract-path: .tmp

      - name: Install opkg-utils (OpenWrt official)
        run: |
          git clone https://git.yoctoproject.org/opkg-utils

      - name: make opkg
        run: |
          mkdir -p dist/gh-pages/opkg
          _pkg_version=${{ github.event.release.tag_name }}
          export _pkg_version=${_pkg_version#v}
          ./packages/smhub-opkg/make-pkg.sh $_pkg_version .tmp/go-tydom .tmp-opkg dist/gh-pages/opkg/go-tydom_${{ github.event.release.tag_name }}.ipk
          rm -rf .tmp .tmp-opkg

      - name: Generate opkg index
        run: |
          cd dist/gh-pages/opkg
          ../../../opkg-utils/opkg-make-index . > Packages
          gzip -c Packages > Packages.gz

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/gh-pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
